name: project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  carousel_slider: 4.2.1
  provider: 6.0.5
  http: 0.13.5
  image_picker: 0.8.7
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  fonts: 
    - family: Lobster
      fonts: 
        - asset: assets/fonts/Lobster-Regular.ttf
  assets: 
    - assets/images/minggu3/
  uses-material-design: true

